swagger-general-config.app.name=Household Store
swagger-general-config.app.description=Household Store - application for  trade management
swagger-general-config.app.version=1.0.0
swagger-general-config.contact.name=Support
swagger-general-config.contact.email=gal85@bk.ru
swagger-general-config.license.name=Proprietary