# For production - minimal logs
spring.jpa.show-sql=false
spring.liquibase.contexts=production

# Only validate!
spring.jpa.hibernate.ddl-auto=validate

# More strict logs
logging.level.ru.galtor85=WARN
logging.level.liquibase=WARN