# ==================================================
# ПРОФИЛЬ LOCAL
# ==================================================
spring.sql.init.mode=never
# Остальные настройки наследуются из основного файла