# ==================================================
#LOCAL
# ==================================================
spring.sql.init.mode=never

server.port=8080
server.ssl.enabled=false

app.defaults.admin.email=admin@household.store
app.defaults.admin.password=Admin123!
app.defaults.admin.first-name=Admin
app.defaults.admin.last-name=Admin
app.defaults.admin.role=ADMIN

app.defaults.manager.email=manager@household.store
app.defaults.manager.password=Manager123!
app.defaults.manager.first-name=Manager
app.defaults.manager.last-name=Manager
app.defaults.manager.role=MANAGER
app.defaults.manager.user-type=EMPLOYEE
