# ==================================================
# ПРОФИЛЬ DOCKER
# ==================================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://household-postgres:5432/household_store?currentSchema=household_schema}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:household_app}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:household123}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.sql.init.mode=never
logging.level.org.springdoc=INFO
logging.level.ru.galtor85=INFO
# Остальное наследуется из основного файла