# Для продакшена - минимум логов
spring.jpa.show-sql=false
spring.liquibase.contexts=production

# Только validate!
spring.jpa.hibernate.ddl-auto=validate

# Более строгие логи
logging.level.ru.galtor85=WARN
logging.level.liquibase=WARN