# ==================================================
#LOCAL
# ==================================================
spring.sql.init.mode=never

server.port=8080
server.ssl.enabled=false

app.defaults.admin.email=admin@household.store
app.defaults.admin.password=Admin123!
app.defaults.admin.first-name=Admin
app.defaults.admin.last-name=Admin
app.defaults.admin.role=ADMIN